version: '3.8'

services:
  mysqldb:
    container_name: mysql_container
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native-password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
